# NumPy, 
short for Numerical Python, is one of the most important foundational packages for numerical computing in Python. Most computational packages providing scientific functionality use NumPy’s array objects as the lingua franca for data exchange.

# Benefits and characteristics of NumPy arrays
NumPy arrays have several advantages over Python lists. These benefits are focused
on providing high-performance manipulation of sequences of homogenous data
items. Several of these benefits are as follows:

• Contiguous allocation in memory

• Vectorized operations

• Boolean selection

• Sliceability

# Contiguous allocation in memory:
provides benefits in performance by ensuring that
all elements of an array are directly accessible at a fixed offset from the beginning
of the array. This also is a computer organization technique that facilities providing
vectorized operations across arrays.

# Vectorized operation:
is a technique of applying an operation across all or a subset
of elements without explicit coding of loops. Vectorized operations are often orders
of magnitude more efficient in execution as compared to loops implemented in a
higher-level language. They are also excellent for reducing the amount of code that
needs to be written, which also helps in minimizing coding errors.

# Boolean selection:
is a common pattern that we will see with NumPy and pandas
where selection of elements from an array is based on specific logical criteria. This
consists of calculating an array of Boolean values where True represents that the
given item should be in the result set. This array can then be used to efficiently select
the matching items.

# Sliceability
provides the programmer with a very efficient means to specify multiple
elements in an array using a convenient notation. Slicing becomes invaluable when
working with data in an ad hoc manner. The slicing process also benefits from being
able to take advantage of the contiguous memory allocation of arrays to optimize
access to series of items.

# Example:
to see the benefits of Contimuous Allocation of memory and Vectorize operation.
The following example calculates the time required by the for loop in Python to square a list consisting of 100,000 sequential integers:

In [1]:
def squares(values):
    result = []
    for v in values:
        result.append(v * v)
    return result

In [2]:
to_square = range(100000)

# time how long it takes to repeatedly square them all

In [3]:
%timeit squares(to_square)

23 ms ± 1.64 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


# Using NumPy and vectorized arrays:
The example can be rewritten as follows

In [4]:
import numpy as np
# now lets do this with a numpy array
array_to_square = np.arange(0, 100000)


# and time using a vectorized operation
%timeit array_to_square ** 2

83.4 µs ± 2.08 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


# Creating NumPy arrays and performing basic array operations

In [5]:
# # methods 1

# A NumPy array can be created using multiple techniques. The following code creates a new NumPy array object from a Python list:

In [6]:
arr1 = np.array([11, 22, 33, 44, 55])
arr1

array([11, 22, 33, 44, 55])

In [7]:
# We can find the type of array, size of array, shape or array and dtype of elements 

In [8]:
type(arr1)

numpy.ndarray

In [9]:
np.size(arr1)

5

In [10]:
arr1.dtype

dtype('int64')

In [11]:
testArr = np.array([1,2,3,4,5.2])
testArr

array([1. , 2. , 3. , 4. , 5.2])

In [12]:
arr1.ndim #returns the dimenssion of the array either it is 1d, 2d, 3d or nd

1

1d array =[1,2,3]>>> vector dimension>>1
2d array = [[1,2,3],[2,3,4]]>>matrix/tensor >>2

In [13]:
# # method 2

# We can create a python range into numpyy array

In [14]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.shape(arr1)

(5,)

In [16]:
# # method 3

# make "a range" starting at 0 and with 10 values np.arange(0, 10)

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# 0 <= x < 10 increment by two
np.arange(0, 10, 2)  #starting, numberofvalues, step

array([0, 2, 4, 6, 8])

In [19]:
# 10 >= x > 0, counting down
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [20]:
# evenly spaced #'s between two intervals
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

# Array creation functions

![NumpyArrayCreationFunctions.png](attachment:NumpyArrayCreationFunctions.png)

# Expicitly Convert /Cast Data type of ndarray

In [21]:
int_arr = np.array([100, 200, 300, 400, 500])
int_arr.dtype

dtype('int64')

In [22]:
float_arr = int_arr.astype(np.float64)
float_arr.dtype

dtype('float64')

# Note:
Casting floating point into integer data type will truncate the decimal part

In [23]:
arr2 = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr2

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [24]:
arr3 = arr2.astype(np.int32)
arr3

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

# Arithmetic with NumPy Arrays

NumPy arrays will vectorize many mathematical operators. The following example
creates a 10-element array and then multiplies each element by a constant:

In [25]:
# multiply numpy array by 2
a1 = np.arange(0, 10)
a1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
# add two numpy arrays
a2 = np.arange(10, 20)
a1 + a2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

# Accessing 1-D array elements:

In [27]:
a2[0]

10

In [28]:
a2[-1]

19

In [29]:
# select 0-based elements 0 and 2
a1[0], a1[2]

(0, 2)

# 2d numpy Array

In [30]:
# Creating a 2d array by python list 

In [31]:
arr2d = np.array([[1,2,3,4,5,6], [11,22,33,44,55,66]])
arr2d

array([[ 1,  2,  3,  4,  5,  6],
       [11, 22, 33, 44, 55, 66]])

A more convenient and efficient means is to use the NumPy array's 

       >>> np.reshape()<<<<
       
method to reorganize a one-dimensional array into two dimensions.

In [32]:
arr1d = np.arange(20)
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
arr2d = arr1d.reshape(4,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [34]:
arr2d = np.arange(20).reshape(4,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [35]:
# size of any dimensional array is the # of elements
np.size(arr2d)

20

In [36]:
# can ask the size along a given axis (0 is rows)
np.size(arr2d, 0)

4

In [37]:
# and 1 is the columns
np.size(arr2d, 1)

5

In [38]:
arr2d.shape

(4, 5)

In [39]:
# a 2d array again can be reshaped to 1d

In [40]:
# arr1d = arr2d.reshape(20)  # in this way we need to know how many elements are there in original array
# print(arr1d)                      # we are open to reshape to any dimension either 1d or other

print("======================================================")
# reshaping a 2darray to 3darray
arr2d = np.arange(64).reshape(8,8)

print(arr2d)

print("============================")
arr3d = arr2d.reshape(2,4,8)  #(depth, rows,columns)
arr3d

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]


array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]],

       [[32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]]])

In [41]:
# #             >>>>>np.ravel()>>>>>
# is another methods but it direclty converts the array to 1d only

In [42]:
raveled_arr1d = arr2d.ravel()
raveled_arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [43]:
#                             >>>>>>>>np.ravel() and np.reshape()<<<<<<<<<

In [44]:
# Even though .reshape() and .ravel() do not change the shape of the original
# array or matrix, they do actually return a one-dimensional view into the specified
# array or matrix. If you change an element in this view, the value in the original array
# or matrix is changed. The following example demonstrates this ability to change
# items of the original matrix through the view:

In [45]:
raveled_arr1d[0]=999
raveled_arr1d

array([999,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63])

In [46]:
arr2d  # array shows the effect of change in ravel

array([[999,   1,   2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31],
       [ 32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60,  61,  62,  63]])

In [47]:
array2d = np.arange(9).reshape(3,3)
array2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
array1d=array2d.reshape(9)
array1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
array1d[0]=777.0
array1d

array([777,   1,   2,   3,   4,   5,   6,   7,   8])

In [50]:
array2d # show the change done in array1d coz array 1d is view of array2d

array([[777,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8]])

In [51]:
# #             >>>>>np.flatten()>>>>>

# is another methods but it direclty converts the array to 1d only. The .flatten() method functions similarly to .ravel() but instead returns a new
# array with copied data instead of a view. Changes to the result do not change the
# original matrix:

In [52]:
array = np.arange(25).reshape(5,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
flattened_array = array.flatten()
flattened_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
flattened_array[0]=555
flattened_array

array([555,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [55]:
array # there is no effect in original

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# np.resize() Danger!!!!

In [56]:
# The .resize() method functions similarly to the .reshape() method, except
# that while reshaping returns a new array with data copied into it, .resize()
# performs an in-place reshaping of the array.:

In [57]:
newarray = np.arange(0, 9).reshape(3,3)
newarray

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
resized = newarray.resize(1,9)
resized  # it is returning none infact it changed the original data

In [59]:
newarray

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

# Basic Indexing and Slicing of Multidimensional Arrays

In [60]:
ar2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ar2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Indexing:
It is a process in which we target(access)indvidual or group of contagious values of ndarrays.

In [61]:
# accessing a complete row 
ar2d[2]

array([7, 8, 9])

In [62]:
# accessing a complete columns
ar2d[:,1]

array([2, 5, 8])

In [63]:
# accessing an element of a 2d array
d2array = np.arange(25).reshape(5,5)
d2array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

![2daray.png](attachment:2daray.png)

In [64]:
#d2array[2,2]
d2array[2][2]

12

![2daray2.png](attachment:2daray2.png)

In [65]:
d2array[0,3], d2array[1,2],d2array[2,4],d2array[4,1]

(3, 7, 14, 21)

# Structure  for indexing and slicing in a 2darray 

![2daray_struc.png](attachment:2daray_struc.png)

![2daray3.png](attachment:2daray3.png)

In [66]:
#Light Blue
d2array[0:4,1:2]

array([[ 1],
       [ 6],
       [11],
       [16]])

In [67]:
#yellow
d2array[1:5,0:3]

array([[ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17],
       [20, 21, 22]])

In [68]:
#blue
d2array[0:2,-2:]

array([[3, 4],
       [8, 9]])

In [69]:
#green
d2array[3:,2:]

array([[17, 18, 19],
       [22, 23, 24]])

![2dSlicing.png](attachment:2dSlicing.png)

# Question:
What is the difference between indexing and slicing ??

# Indexing:
Targets the element of the array. The returned is the individual vlaue or group of values having their own data types.

In [70]:
d2array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [71]:
d2array[4][2]   # returns and element of the array 22 that is int type 

22

# Slicing:
Gives the part of the array that have the same deimension(shape) as the full array has.

In [72]:
d2array[1:4,2:3]   # notice the brackets around 22 shows its not an element but a 2d array with one element 22.

array([[ 7],
       [12],
       [17]])

# Combining array

Arrays can be combined in various ways. This process in NumPy is referred to
as stacking. Stacking can take various forms, including horizontal, vertical, and
depth-wise stacking. To demonstrate this, we will use the following two arrays

# Horizontal stacking

Combines two arrays in a manner where the columns of the
second array are placed to the right of those in the first array. The function actually
stacks the two items provided in a two-element tuple. The result is a new array with
data copied from the two that are specified:

In [73]:
arr1 = np.arange(16).reshape(8,2)
arr1

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [74]:
arr2 = np.arange(16,56).reshape(8,5)
arr2

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55]])

In [75]:
np.hstack((arr1, arr2))

array([[ 0,  1, 16, 17, 18, 19, 20],
       [ 2,  3, 21, 22, 23, 24, 25],
       [ 4,  5, 26, 27, 28, 29, 30],
       [ 6,  7, 31, 32, 33, 34, 35],
       [ 8,  9, 36, 37, 38, 39, 40],
       [10, 11, 41, 42, 43, 44, 45],
       [12, 13, 46, 47, 48, 49, 50],
       [14, 15, 51, 52, 53, 54, 55]])

# Vertical Stacking
Vertical stacking returns a new array with the contents of the second array as
appended rows of the first array.

In [76]:
arr3 = np.arange(20).reshape(2,10)
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [77]:
arr4 = np.arange(20,60).reshape(4,10)
arr4

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [78]:
np.vstack((arr4,arr3))

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

# Columns stacking 

# Row Stacking

# Depth stacking
takes a list of arrays and arranges them in order along an additional
axis referred to as the depth:

In [79]:
arr5 = np.arange(9).reshape(3,3)
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [80]:
arr6 = np.arange(9,18).reshape(3,3)
arr6

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [81]:
np.dstack((arr5,arr6))

array([[[ 0,  9],
        [ 1, 10],
        [ 2, 11]],

       [[ 3, 12],
        [ 4, 13],
        [ 5, 14]],

       [[ 6, 15],
        [ 7, 16],
        [ 8, 17]]])

# Useful numerical methods of NumPy arrays

In [82]:
# demonstrate some of the properties of NumPy arrays
m = np.arange(10, 19).reshape(3, 3)
print (m)
print ("{0} min of the entire matrix".format(m.min()))
print ("{0} max of entire matrix".format(m.max()))
print ("{0} position of the min value".format(m.argmin()))
print ("{0} position of the max value".format(m.argmax()))
print ("{0} mins down each column".format(m.min(axis = 0)))
print ("{0} mins across each row".format(m.min(axis = 1)))
print ("{0} maxs down each column".format(m.max(axis = 0)))

[[10 11 12]
 [13 14 15]
 [16 17 18]]
10 min of the entire matrix
18 max of entire matrix
0 position of the min value
8 position of the max value
[10 11 12] mins down each column
[10 13 16] mins across each row
[16 17 18] maxs down each column


# Some statiscal function 

In [83]:
my_array = np.arange(36).reshape(6,6)
my_array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [84]:
print(f"The mean of the array is {my_array.mean()}, \nThe standard devition is {my_array.std()},\nand the variation is {my_array.var()}")

The mean of the array is 17.5, 
The standard devition is 10.388294694831615,
and the variation is 107.91666666666667


In [85]:
print(f"The sum of array is {my_array.sum()}, \nand the product is {my_array.prod()} ")

The sum of array is 630, 
and the product is 0 


In [86]:
print(f"The sum of array is {my_array.cumsum()}, \nand the product is {my_array.cumprod()} ")

The sum of array is [  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190 210 231 253 276 300 325 351 378 406 435 465 496 528 561 595 630], 
and the product is [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 


# Applying Logical Operators on arrays

In [87]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
# .any() returns true if any of the values us less than 5 
# and .all() return true if and only if all the values are less than 5

(a < 5).any()

True

In [89]:
(a < 5). all()

False

In [90]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [91]:
data =np.array(np.random.randn(7, 4)*10,dtype=np.int)
data

array([[  8,   8, -10,  -1],
       [  6, -14,   0,   0],
       [ 21, -14,   6,   1],
       [  0,  11,  13,   0],
       [-13,   8, -21, -14],
       [  3,  10,   6,  13],
       [  9,   5, -15, -27]])

Suppose each name corresponds to a row in the data array and we wanted to select
all the rows with corresponding name 'Bob'.

Like arithmetic operations, comparisons (such as ==) with arrays are also vectorized.

Thus, comparing names with the
string 'Bob' yields a boolean array:

![booleanSelection.png](attachment:booleanSelection.png)

First consdier this, if we wnat to select (fancy selection) different rows from array we can pass a list of row indices.

But a big but, if we want to select different rows based on some criteria like here we want all rows corresponding to name 'Bob' 

we will do booean indexing

In [92]:
# fancy indexing 
data[[0,6]]

array([[  8,   8, -10,  -1],
       [  9,   5, -15, -27]])

In [93]:
#boolean indexing now

names == 'Bob' # vectorize comparision,will return true where name is bob in names array.

array([ True, False, False,  True, False, False, False])

In [94]:
# this result can be passed in to data array to select true rows based on true and false (booleans)

In [95]:
data[[ True, False, False,  True, False, False, False]] # this way

array([[  8,   8, -10,  -1],
       [  0,  11,  13,   0]])

In [96]:
# a better ways is :
data[names=='Bob']  # definitely inside data brackets boolean array will be generated by names=='Bob'

array([[  8,   8, -10,  -1],
       [  0,  11,  13,   0]])

In [97]:
data[names!='Bob']

array([[  6, -14,   0,   0],
       [ 21, -14,   6,   1],
       [-13,   8, -21, -14],
       [  3,  10,   6,  13],
       [  9,   5, -15, -27]])

In [98]:
# Selecting two of the three names to combine multiple boolean conditions, use
# boolean arithmetic operators like & (and) and | (or):

In [99]:
mask = (names == 'Bob') | (names == 'Will') 


#this is multiple names condition genearting a sort of mask to provide to data array

####The Python keywords and and or do not work with boolean arrays.##############

#####################Use & (and) and | (or) instead.#############################

In [100]:
data[mask]

array([[  8,   8, -10,  -1],
       [ 21, -14,   6,   1],
       [  0,  11,  13,   0],
       [-13,   8, -21, -14]])

In [101]:
data[data < 0] = 0  # another way! It replaces all the values on true indexings with 0

In [102]:
data

array([[ 8,  8,  0,  0],
       [ 6,  0,  0,  0],
       [21,  0,  6,  1],
       [ 0, 11, 13,  0],
       [ 0,  8,  0,  0],
       [ 3, 10,  6, 13],
       [ 9,  5,  0,  0]])

# Fancy Indexing

In [103]:
data[[2,2]]

array([[21,  0,  6,  1],
       [21,  0,  6,  1]])

In [104]:
data[[-1,-2]]

array([[ 9,  5,  0,  0],
       [ 3, 10,  6, 13]])

# Transposing Arrays and Swapping Axes

In [105]:
data.T

array([[ 8,  6, 21,  0,  0,  3,  9],
       [ 8,  0,  0, 11,  8, 10,  5],
       [ 0,  0,  6, 13,  0,  6,  0],
       [ 0,  0,  1,  0,  0, 13,  0]])

In [106]:
np.transpose(data)

array([[ 8,  6, 21,  0,  0,  3,  9],
       [ 8,  0,  0, 11,  8, 10,  5],
       [ 0,  0,  6, 13,  0,  6,  0],
       [ 0,  0,  1,  0,  0, 13,  0]])

# Universal Functions: Fast Element-Wise Array Functions

In [107]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [109]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [110]:
x = np.random.randn(8)
y = np.random.randn(8)

In [111]:
np.maximum(x, y) #compares both arrays element wise and max is included in result

array([ 0.89092347,  0.14883431, -0.04087864, -0.03774544, -0.17725212,
       -0.86327697, -1.60560538,  0.07277605])

In [112]:
arr = np.random.randn(7) * 5
arr

array([-4.51212235,  5.29058615, -2.75232947,  5.61671927,  0.33790782,
       -2.81039604, -1.45035864])

In [113]:
remainder, whole_part = np.modf(arr) #modf separate whole n decimal parts and return them 

In [114]:
remainder

array([-0.51212235,  0.29058615, -0.75232947,  0.61671927,  0.33790782,
       -0.81039604, -0.45035864])

In [115]:
whole_part

array([-4.,  5., -2.,  5.,  0., -2., -1.])

# List of unary funcs (Ufuncs)
take single array input

![unaryfuncs.png](attachment:unaryfuncs.png)

# List of binary funcs:
    take to arrays input

![Binaryfuncs.png](attachment:Binaryfuncs.png)

# Linear Algebra

Like matrix multiplication, decompositions, determinants, and other square matrix math, is an important part of any array library. Unlike some languages like MATLAB, multiplying two two-dimensional arrays with * sign is an element-wise
product instead of a matrix dot product. Thus, there is a function dot, both an array method and a function in the numpy namespace, for matrix multiplication.

In [116]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [117]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

# Note:
    to multiply two matices (element wise multiplication or mirror multiplication) both matrix must have same shape. 

In [118]:
x*y

ValueError: ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In linear algebra rows of first matrix is multiplied by the columns of second matrix and this is only possilbe
when columns of first matrix are equal to the rows of second matrix

![matrixMult.png](attachment:matrixMult.png)

In [119]:
# order of x
x.shape

(2, 3)

In [120]:
# order of y
y.shape

(3, 2)

In [121]:
# col of x ==  rows of y 
# hence matrix multiplication can be done

In [122]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [123]:
np.dot(y,x)  # y.y also fulfilling the rule

array([[ 98., 127., 156.],
       [ 27.,  33.,  39.],
       [ 44.,  61.,  78.]])

# Note:
it is not neccesary if a.b is possible so b.a will be. 

np.dot(a,b)  

a.dot(b)


a@b

All are same

# numpy.linalg

In [124]:
# has a standard set of matrix decompositions and things like inverse
# and determinant. These are implemented under the hood via the same industrystandard linear algebra libraries used in other languages like MATLAB and R, such as
# BLAS, LAPACK, or possibly (depending on your NumPy build) the proprietary Intel
# MKL (Math Kernel Library):

In [125]:
from numpy.linalg import inv, qr

In [126]:
X = np.array((np.random.randn(5, 5)*10),dtype='int32')
X

array([[-11, -13,  -8, -21,   1],
       [  8,  20, -18,  -2, -14],
       [  2, -14,   1,   0,  -7],
       [ 16,   6, -10,  -2,  20],
       [ -3,  12,   3,  11,   2]], dtype=int32)

In [127]:
inv(X)

array([[-0.05821858,  0.00325178, -0.03345186,  0.00445339, -0.10974363],
       [-0.02373768,  0.00817853, -0.08608194, -0.01849747, -0.04719356],
       [-0.07118137, -0.03009717, -0.12514446, -0.04633074, -0.1497877 ],
       [ 0.02567228,  0.00375997,  0.11857441,  0.02827497,  0.14574435],
       [ 0.02067271, -0.01972757,  0.00187128,  0.03164866,  0.04163355]])

The expression X.T.dot(X) computes the dot product of X with its transpose X.T.

In [128]:
mat = X.T.dot(X)
mat

array([[ 454,  335, -223,  150,  177],
       [ 335,  945, -294,  353,  -51],
       [-223, -294,  498,  257,   43],
       [ 150,  353,  257,  570,  -11],
       [ 177,  -51,   43,  -11,  650]], dtype=int32)

![numpyLinAlg.png](attachment:numpyLinAlg.png)